Q6.Using the data from Question 3, write code to analyze the data and answer the following questions 

Note 
1. Draw plots to demonstrate the analysis for the following questions for better visualizations.
2. Write code comments wherever required for code understanding

Insights to be drawn -
- Get all Pokemons whose spawn rate is less than 5%
- Get all Pokemons that have less than 4 weaknesses
- Get all Pokemons that have no multipliers at all
- Get all Pokemons that do not have more than 2 evolutions
- Get all Pokemons whose spawn time is less than 300 seconds.
Note - spawn time format is "05:32”, so assume “minute: second” format and perform the analysis.
- Get all Pokemon who have more than two types of capabilities

In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('ques-3.xlsx')

In [3]:
df.head()

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution
0,1,1,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"['Grass', 'Poison']",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,0.690,69.0,20:00,[1.58],"['Fire', 'Ice', 'Flying', 'Psychic']","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN
1,2,2,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"['Grass', 'Poison']",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,0.042,4.2,07:00,"[1.2, 1.6]","['Fire', 'Ice', 'Flying', 'Psychic']","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]"
2,3,3,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"['Grass', 'Poison']",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,0.017,1.7,11:30,NaN,"['Fire', 'Ice', 'Flying', 'Psychic']",NaN,"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ..."
3,4,4,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,['Fire'],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,0.253,25.3,08:45,[1.65],"['Water', 'Ground', 'Rock']","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",NaN
4,5,5,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,['Fire'],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.012,1.2,19:00,[1.79],"['Water', 'Ground', 'Rock']","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]"

### Get all Pokemons whose spawn rate is less than 5%

In [4]:
df[df['avg_spawns']<5]

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution
1,2,2,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"['Grass', 'Poison']",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,0.0420,4.20,07:00,"[1.2, 1.6]","['Fire', 'Ice', 'Flying', 'Psychic']","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]"
2,3,3,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"['Grass', 'Poison']",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,0.0170,1.70,11:30,NaN,"['Fire', 'Ice', 'Flying', 'Psychic']",NaN,"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ..."
4,5,5,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,['Fire'],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.0120,1.20,19:00,[1.79],"['Water', 'Ground', 'Rock']","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]"
5,6,6,Charizard,http://www.serebii.net/pokemongo/pokemon/006.png,"['Fire', 'Flying']",1.70 m,90.5 kg,Charmander Candy,NaN,Not in Eggs,0.0031,0.31,13:34,NaN,"['Water', 'Electric', 'Rock']",NaN,"[{'num': '004', 'name': 'Charmander'}, {'num':..."
7,8,8,Wartortle,http://www.serebii.net/pokemongo/pokemon/008.png,['Water'],0.99 m,22.5 kg,Squirtle Candy,100.0,Not in Eggs,0.0340,3.40,07:02,[1.4],"['Electric', 'Grass']","[{'num': '009', 'name': 'Blastoise'}]","[{'num': '007', 'name': 'Squirtle'}]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,146,146,Moltres,http://www.serebii.net/pokemongo/pokemon/146.png,"['Fire', 'Flying']",2.01 m,60.0 kg,None,NaN,Not in Eggs,0.0000,0.00,NaN,NaN,"['Water', 'Electric', 'Rock']",NaN,NaN
147,148,148,Dragonair,http://www.serebii.net/pokemongo/pokemon/148.png,['Dragon'],3.99 m,16.5 kg,Dratini Candy,100.0,Not in Eggs,0.0200,2.00,11:57,[2.05],"['Ice', 'Dragon', 'Fairy']","[{'num': '149', 'name': 'Dragonite'}]","[{'num': '147', 'name': 'Dratini'}]"
148,149,149,Dragonite,http://www.serebii.net/pokemongo/pokemon/149.png,"['Dragon', 'Flying']",2.21 m,210.0 kg,Dratini Candy,NaN,Not in Eggs,0.0011,0.11,23:38,NaN,"['Ice', 'Rock', 'Dragon', 'Fairy']",NaN,"[{'num': '147', 'name': 'Dratini'}, {'num': '1..."
149,150,150,Mewtwo,http://www.serebii.net/pokemongo/pokemon/150.png,['Psychic'],2.01 m,122.0 kg,None,NaN,Not in Eggs,0.0000,0.00,NaN,NaN,"['Bug', 'Ghost', 'Dark']",NaN,NaN
150,151,151,Mew,http://www.serebii.net/pokemongo/pokemon/151.png,['Psychic'],0.41 m,4.0 kg,None,NaN,Not in Eggs,0.0000,0.00,NaN,NaN,"['Bug', 'Ghost', 'Dark']",NaN,NaN

In [5]:
df.loc[df['avg_spawns']<5,'name'].unique()

array(['Ivysaur', 'Venusaur', 'Charmeleon', 'Charizard', 'Wartortle',
       'Blastoise', 'Butterfree', 'Pidgey', 'Rattata', 'Raichu',
       'Sandslash', 'Nidoqueen', 'Nidoking', 'Clefable', 'Ninetales',
       'Wigglytuff', 'Vileplume', 'Dugtrio', 'Persian', 'Primeape',
       'Arcanine', 'Poliwrath', 'Kadabra', 'Alakazam', 'Machoke',
       'Machamp', 'Victreebel', 'Golem', 'Rapidash', 'Slowbro',
       'Magneton', "Farfetch'd", 'Dewgong', 'Muk', 'Cloyster', 'Gengar',
       'Electrode', 'Exeggutor', 'Marowak', 'Hitmonlee', 'Hitmonchan',
       'Lickitung', 'Weezing', 'Rhydon', 'Chansey', 'Kangaskhan',
       'Seadra', 'Starmie', 'Mr. Mime', 'Gyarados', 'Lapras', 'Ditto',
       'Vaporeon', 'Jolteon', 'Flareon', 'Porygon', 'Omastar', 'Kabutops',
       'Aerodactyl', 'Snorlax', 'Articuno', 'Zapdos', 'Moltres',
       'Dragonair', 'Dragonite', 'Mewtwo', 'Mew'], dtype=object)

### Get all Pokemons that have less than 4 weaknesses

In [6]:
import ast
df['weaknesses']=df['weaknesses'].apply(ast.literal_eval)

In [7]:
df[df['weaknesses'].apply(lambda i : len(i)<4)]

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution
3,4,4,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,['Fire'],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,0.2530,25.30,08:45,[1.65],"[Water, Ground, Rock]","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",NaN
4,5,5,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,['Fire'],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.0120,1.20,19:00,[1.79],"[Water, Ground, Rock]","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]"
5,6,6,Charizard,http://www.serebii.net/pokemongo/pokemon/006.png,"['Fire', 'Flying']",1.70 m,90.5 kg,Charmander Candy,NaN,Not in Eggs,0.0031,0.31,13:34,NaN,"[Water, Electric, Rock]",NaN,"[{'num': '004', 'name': 'Charmander'}, {'num':..."
6,7,7,Squirtle,http://www.serebii.net/pokemongo/pokemon/007.png,['Water'],0.51 m,9.0 kg,Squirtle Candy,25.0,2 km,0.5800,58.00,04:25,[2.1],"[Electric, Grass]","[{'num': '008', 'name': 'Wartortle'}, {'num': ...",NaN
7,8,8,Wartortle,http://www.serebii.net/pokemongo/pokemon/008.png,['Water'],0.99 m,22.5 kg,Squirtle Candy,100.0,Not in Eggs,0.0340,3.40,07:02,[1.4],"[Electric, Grass]","[{'num': '009', 'name': 'Blastoise'}]","[{'num': '007', 'name': 'Squirtle'}]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,146,146,Moltres,http://www.serebii.net/pokemongo/pokemon/146.png,"['Fire', 'Flying']",2.01 m,60.0 kg,None,NaN,Not in Eggs,0.0000,0.00,NaN,NaN,"[Water, Electric, Rock]",NaN,NaN
146,147,147,Dratini,http://www.serebii.net/pokemongo/pokemon/147.png,['Dragon'],1.80 m,3.3 kg,Dratini Candy,25.0,10 km,0.3000,30.00,06:41,"[1.83, 1.84]","[Ice, Dragon, Fairy]","[{'num': '148', 'name': 'Dragonair'}, {'num': ...",NaN
147,148,148,Dragonair,http://www.serebii.net/pokemongo/pokemon/148.png,['Dragon'],3.99 m,16.5 kg,Dratini Candy,100.0,Not in Eggs,0.0200,2.00,11:57,[2.05],"[Ice, Dragon, Fairy]","[{'num': '149', 'name': 'Dragonite'}]","[{'num': '147', 'name': 'Dratini'}]"
149,150,150,Mewtwo,http://www.serebii.net/pokemongo/pokemon/150.png,['Psychic'],2.01 m,122.0 kg,None,NaN,Not in Eggs,0.0000,0.00,NaN,NaN,"[Bug, Ghost, Dark]",NaN,NaN
150,151,151,Mew,http://www.serebii.net/pokemongo/pokemon/151.png,['Psychic'],0.41 m,4.0 kg,None,NaN,Not in Eggs,0.0000,0.00,NaN,NaN,"[Bug, Ghost, Dark]",NaN,NaN

In [8]:
df[df['weaknesses'].apply(lambda i : len(i)<4)]['name'].unique()

array(['Charmander', 'Charmeleon', 'Charizard', 'Squirtle', 'Wartortle',
       'Blastoise', 'Caterpie', 'Metapod', 'Pidgey', 'Pidgeotto',
       'Pidgeot', 'Rattata', 'Raticate', 'Spearow', 'Fearow', 'Ekans',
       'Arbok', 'Pikachu', 'Raichu', 'Sandshrew', 'Sandslash',
       'Nidoran ♀ (Female)', 'Nidorina', 'Nidoran ♂ (Male)', 'Nidorino',
       'Clefairy', 'Clefable', 'Vulpix', 'Ninetales', 'Jigglypuff',
       'Wigglytuff', 'Diglett', 'Dugtrio', 'Meowth', 'Persian', 'Psyduck',
       'Golduck', 'Mankey', 'Primeape', 'Growlithe', 'Arcanine',
       'Poliwag', 'Poliwhirl', 'Abra', 'Kadabra', 'Alakazam', 'Machop',
       'Machoke', 'Machamp', 'Tentacool', 'Tentacruel', 'Ponyta',
       'Rapidash', 'Magnemite', 'Magneton', "Farfetch'd", 'Doduo',
       'Dodrio', 'Seel', 'Grimer', 'Muk', 'Shellder', 'Drowzee', 'Hypno',
       'Krabby', 'Kingler', 'Voltorb', 'Electrode', 'Cubone', 'Marowak',
       'Hitmonlee', 'Hitmonchan', 'Lickitung', 'Koffing', 'Weezing',
       'Chansey', 'Kangaskhan', 'Horsea', 'Seadra', 'Goldeen', 'Seaking',
       'Staryu', 'Mr. Mime', 'Electabuzz', 'Magmar', 'Pinsir', 'Tauros',
       'Magikarp', 'Gyarados', 'Ditto', 'Eevee', 'Vaporeon', 'Jolteon',
       'Flareon', 'Porygon', 'Snorlax', 'Zapdos', 'Moltres', 'Dratini',
       'Dragonair', 'Mewtwo', 'Mew'], dtype=object)

### Get all Pokemons that have no multipliers at all

In [9]:
df[df['multipliers'].isna()]

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution
2,3,3,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"['Grass', 'Poison']",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,0.0170,1.70,11:30,NaN,"[Fire, Ice, Flying, Psychic]",NaN,"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ..."
5,6,6,Charizard,http://www.serebii.net/pokemongo/pokemon/006.png,"['Fire', 'Flying']",1.70 m,90.5 kg,Charmander Candy,NaN,Not in Eggs,0.0031,0.31,13:34,NaN,"[Water, Electric, Rock]",NaN,"[{'num': '004', 'name': 'Charmander'}, {'num':..."
8,9,9,Blastoise,http://www.serebii.net/pokemongo/pokemon/009.png,['Water'],1.60 m,85.5 kg,Squirtle Candy,NaN,Not in Eggs,0.0067,0.67,00:06,NaN,"[Electric, Grass]",NaN,"[{'num': '007', 'name': 'Squirtle'}, {'num': '..."
11,12,12,Butterfree,http://www.serebii.net/pokemongo/pokemon/012.png,"['Bug', 'Flying']",1.09 m,32.0 kg,Caterpie Candy,NaN,Not in Eggs,0.0220,2.20,05:23,NaN,"[Fire, Electric, Ice, Flying, Rock]",NaN,"[{'num': '010', 'name': 'Caterpie'}, {'num': '..."
14,15,15,Beedrill,http://www.serebii.net/pokemongo/pokemon/015.png,"['Bug', 'Poison']",0.99 m,29.5 kg,Weedle Candy,NaN,Not in Eggs,0.0510,5.10,04:50,NaN,"[Fire, Flying, Psychic, Rock]",NaN,"[{'num': '013', 'name': 'Weedle'}, {'num': '01..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,145,145,Zapdos,http://www.serebii.net/pokemongo/pokemon/145.png,"['Electric', 'Flying']",1.60 m,52.6 kg,None,NaN,Not in Eggs,0.0000,0.00,NaN,NaN,"[Ice, Rock]",NaN,NaN
145,146,146,Moltres,http://www.serebii.net/pokemongo/pokemon/146.png,"['Fire', 'Flying']",2.01 m,60.0 kg,None,NaN,Not in Eggs,0.0000,0.00,NaN,NaN,"[Water, Electric, Rock]",NaN,NaN
148,149,149,Dragonite,http://www.serebii.net/pokemongo/pokemon/149.png,"['Dragon', 'Flying']",2.21 m,210.0 kg,Dratini Candy,NaN,Not in Eggs,0.0011,0.11,23:38,NaN,"[Ice, Rock, Dragon, Fairy]",NaN,"[{'num': '147', 'name': 'Dratini'}, {'num': '1..."
149,150,150,Mewtwo,http://www.serebii.net/pokemongo/pokemon/150.png,['Psychic'],2.01 m,122.0 kg,None,NaN,Not in Eggs,0.0000,0.00,NaN,NaN,"[Bug, Ghost, Dark]",NaN,NaN
150,151,151,Mew,http://www.serebii.net/pokemongo/pokemon/151.png,['Psychic'],0.41 m,4.0 kg,None,NaN,Not in Eggs,0.0000,0.00,NaN,NaN,"[Bug, Ghost, Dark]",NaN,NaN

In [10]:
df[df['multipliers'].isna()]['name'].unique()

array(['Venusaur', 'Charizard', 'Blastoise', 'Butterfree', 'Beedrill',
       'Pidgeot', 'Raticate', 'Fearow', 'Arbok', 'Raichu', 'Sandslash',
       'Nidoqueen', 'Nidoking', 'Clefable', 'Ninetales', 'Wigglytuff',
       'Golbat', 'Vileplume', 'Parasect', 'Venomoth', 'Dugtrio',
       'Persian', 'Golduck', 'Primeape', 'Arcanine', 'Poliwrath',
       'Alakazam', 'Machamp', 'Victreebel', 'Tentacruel', 'Golem',
       'Rapidash', 'Slowbro', 'Magneton', "Farfetch'd", 'Dodrio',
       'Dewgong', 'Muk', 'Cloyster', 'Gengar', 'Onix', 'Hypno', 'Kingler',
       'Electrode', 'Exeggutor', 'Marowak', 'Hitmonlee', 'Hitmonchan',
       'Lickitung', 'Weezing', 'Rhydon', 'Chansey', 'Tangela',
       'Kangaskhan', 'Seadra', 'Seaking', 'Starmie', 'Mr. Mime',
       'Scyther', 'Jynx', 'Electabuzz', 'Magmar', 'Pinsir', 'Tauros',
       'Gyarados', 'Lapras', 'Ditto', 'Vaporeon', 'Jolteon', 'Flareon',
       'Porygon', 'Omastar', 'Kabutops', 'Aerodactyl', 'Snorlax',
       'Articuno', 'Zapdos', 'Moltres', 'Dragonite', 'Mewtwo', 'Mew'],
      dtype=object)

### Get all Pokemons that do not have more than 2 evolutions

In [11]:
def evolution(i):
    if i==0:
        return 0
    else:
        i = ast.literal_eval(i)
        return len(i)

In [12]:
df['prev_evolution'].fillna(0,inplace=True)
df['next_evolution'].fillna(0,inplace=True)

In [13]:
# created a new column with evolution count
df['evolution_count']= df['prev_evolution'].apply(evolution) + df['next_evolution'].apply(evolution)

In [14]:
df[df['evolution_count']<=2]

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution,evolution_count
0,1,1,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"['Grass', 'Poison']",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,0.6900,69.00,20:00,[1.58],"[Fire, Ice, Flying, Psychic]","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",0,2
1,2,2,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"['Grass', 'Poison']",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,0.0420,4.20,07:00,"[1.2, 1.6]","[Fire, Ice, Flying, Psychic]","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]",2
2,3,3,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"['Grass', 'Poison']",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,0.0170,1.70,11:30,NaN,"[Fire, Ice, Flying, Psychic]",0,"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ...",2
3,4,4,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,['Fire'],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,0.2530,25.30,08:45,[1.65],"[Water, Ground, Rock]","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",0,2
4,5,5,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,['Fire'],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.0120,1.20,19:00,[1.79],"[Water, Ground, Rock]","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]",2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,147,147,Dratini,http://www.serebii.net/pokemongo/pokemon/147.png,['Dragon'],1.80 m,3.3 kg,Dratini Candy,25.0,10 km,0.3000,30.00,06:41,"[1.83, 1.84]","[Ice, Dragon, Fairy]","[{'num': '148', 'name': 'Dragonair'}, {'num': ...",0,2
147,148,148,Dragonair,http://www.serebii.net/pokemongo/pokemon/148.png,['Dragon'],3.99 m,16.5 kg,Dratini Candy,100.0,Not in Eggs,0.0200,2.00,11:57,[2.05],"[Ice, Dragon, Fairy]","[{'num': '149', 'name': 'Dragonite'}]","[{'num': '147', 'name': 'Dratini'}]",2
148,149,149,Dragonite,http://www.serebii.net/pokemongo/pokemon/149.png,"['Dragon', 'Flying']",2.21 m,210.0 kg,Dratini Candy,NaN,Not in Eggs,0.0011,0.11,23:38,NaN,"[Ice, Rock, Dragon, Fairy]",0,"[{'num': '147', 'name': 'Dratini'}, {'num': '1...",2
149,150,150,Mewtwo,http://www.serebii.net/pokemongo/pokemon/150.png,['Psychic'],2.01 m,122.0 kg,None,NaN,Not in Eggs,0.0000,0.00,NaN,NaN,"[Bug, Ghost, Dark]",0,0,0
150,151,151,Mew,http://www.serebii.net/pokemongo/pokemon/151.png,['Psychic'],0.41 m,4.0 kg,None,NaN,Not in Eggs,0.0000,0.00,NaN,NaN,"[Bug, Ghost, Dark]",0,0,0

#### Get all Pokemons whose spawn time is less than 300 seconds. Note - spawn time format is "05:32”, so assume “minute: second” format and perform the analysis.

In [15]:
def convert_time(i):
    mn = int(i[0:2])
    sec = int(i[3:5])
    val = mn*60 + sec
    return val

In [16]:
# filled null values with "00:00"
df['spawn_time'].fillna("00:00",inplace=True)

In [17]:
# converted the spawn_time into seconds
df["spawn_time"] = df['spawn_time'].apply(convert_time)

In [18]:
# pokemons with spawn time less than 300
df[df['spawn_time']<300]

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution,evolution_count
6,7,7,Squirtle,http://www.serebii.net/pokemongo/pokemon/007.png,['Water'],0.51 m,9.0 kg,Squirtle Candy,25.0,2 km,0.5800,58.00,265,[2.1],"[Electric, Grass]","[{'num': '008', 'name': 'Wartortle'}, {'num': ...",0,2
8,9,9,Blastoise,http://www.serebii.net/pokemongo/pokemon/009.png,['Water'],1.60 m,85.5 kg,Squirtle Candy,NaN,Not in Eggs,0.0067,0.67,6,NaN,"[Electric, Grass]",0,"[{'num': '007', 'name': 'Squirtle'}, {'num': '...",2
10,11,11,Metapod,http://www.serebii.net/pokemongo/pokemon/011.png,['Bug'],0.71 m,9.9 kg,Caterpie Candy,50.0,Not in Eggs,0.1870,18.70,131,"[3.55, 3.79]","[Fire, Flying, Rock]","[{'num': '012', 'name': 'Butterfree'}]","[{'num': '010', 'name': 'Caterpie'}]",2
12,13,13,Weedle,http://www.serebii.net/pokemongo/pokemon/013.png,"['Bug', 'Poison']",0.30 m,3.2 kg,Weedle Candy,12.0,2 km,7.1200,712.00,141,"[1.01, 1.09]","[Fire, Flying, Psychic, Rock]","[{'num': '014', 'name': 'Kakuna'}, {'num': '01...",0,2
13,14,14,Kakuna,http://www.serebii.net/pokemongo/pokemon/014.png,"['Bug', 'Poison']",0.61 m,10.0 kg,Weedle Candy,50.0,Not in Eggs,0.4400,44.00,150,"[3.01, 3.41]","[Fire, Flying, Psychic, Rock]","[{'num': '015', 'name': 'Beedrill'}]","[{'num': '013', 'name': 'Weedle'}]",2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143,144,144,Articuno,http://www.serebii.net/pokemongo/pokemon/144.png,"['Ice', 'Flying']",1.70 m,55.4 kg,None,NaN,Not in Eggs,0.0000,0.00,0,NaN,"[Fire, Electric, Rock, Steel]",0,0,0
144,145,145,Zapdos,http://www.serebii.net/pokemongo/pokemon/145.png,"['Electric', 'Flying']",1.60 m,52.6 kg,None,NaN,Not in Eggs,0.0000,0.00,0,NaN,"[Ice, Rock]",0,0,0
145,146,146,Moltres,http://www.serebii.net/pokemongo/pokemon/146.png,"['Fire', 'Flying']",2.01 m,60.0 kg,None,NaN,Not in Eggs,0.0000,0.00,0,NaN,"[Water, Electric, Rock]",0,0,0
149,150,150,Mewtwo,http://www.serebii.net/pokemongo/pokemon/150.png,['Psychic'],2.01 m,122.0 kg,None,NaN,Not in Eggs,0.0000,0.00,0,NaN,"[Bug, Ghost, Dark]",0,0,0
150,151,151,Mew,http://www.serebii.net/pokemongo/pokemon/151.png,['Psychic'],0.41 m,4.0 kg,None,NaN,Not in Eggs,0.0000,0.00,0,NaN,"[Bug, Ghost, Dark]",0,0,0

### Get all Pokemon who have more than two types of capabilities

In [19]:
# converted the string formatted list to list again
df['type'] = df['type'].apply(ast.literal_eval)

In [20]:
type(df['type'][1])

list

In [21]:
df[df['type'].apply(lambda i : len(i)>2)]

Empty DataFrame
Columns: [id, num, name, img, type, height, weight, candy, candy_count, egg, spawn_chance, avg_spawns, spawn_time, multipliers, weaknesses, next_evolution, prev_evolution, evolution_count]
Index: []

In [22]:
df['type'].value_counts()

[Water]               18
[Normal]              16
[Fire]                10
[Poison]              10
[Grass, Poison]        9
[Normal, Flying]       8
[Electric]             8
[Psychic]              8
[Fighting]             7
[Ground]               6
[Bug, Poison]          5
[Rock, Water]          4
[Rock, Ground]         4
[Ghost, Poison]        3
[Water, Psychic]       3
[Water, Ice]           3
[Bug]                  3
[Water, Poison]        2
[Bug, Grass]           2
[Poison, Flying]       2
[Bug, Flying]          2
[Poison, Ground]       2
[Grass, Psychic]       2
[Ground, Rock]         2
[Fire, Flying]         2
[Dragon]               2
[Water, Fighting]      1
[Ice, Flying]          1
[Electric, Flying]     1
[Grass]                1
[Rock, Flying]         1
[Water, Flying]        1
[Ice, Psychic]         1
[Dragon, Flying]       1
Name: type, dtype: int64

### There are no pokemons with more than 2 capabilities